services:
    anavaro.activenotifications.maincontroller:
        class: anavaro\activenotifications\controller\main_controller
        arguments:
            - @config
            - @user
            - @request
            - @notification_manager
            - @dbal.conn
            - @template
    anavaro.activenotifications.listener:
        class: anavaro\activenotifications\event\listener
        arguments:
            - @config
            - @user
            - @template
            - @notification_manager
            - @controller.helper
        tags:
            - { name: event.listener }
